denoland/saaskit

components/Dashboard.tsx
components/LinkButton.tsx
routes/index.tsx

This PR fixes HTML validation errors caught by [the W3C Markup Validation Service](https://validator.w3.org/).

fix: HTML validation errors

---

README.md
routes/index.tsx
twind.config.ts

This PR defines `primary` and `secondary` colors within `twind.config.js` for the site-wide theme, providing a foundation for further theme customization. A corresponding section within the README was also added. This can be expanded upon in the future if need be.
Closes #9.

feat: basic theme customization

---

components/Dashboard.tsx
components/Header.tsx

fix: links not clickable across entire area

---

components/Header.tsx
components/Logo.tsx
components/Nav.tsx
routes/_404.tsx
routes/_500.tsx
routes/index.tsx
routes/login.tsx
routes/signup.tsx

This component has its class adjusted to its `height` attribute.
This PR further adds to #9.

feat: `Logo` component

---

.github/workflows/ci.yml
README.md
deno.json

This change:
1. Introduces a `test` task that must pass for pull requests to be merged.
2. Adds a small **Contributing** guide to the README.

feat: `deno task test` and basic contributing guide

---

README.md
routes/index.tsx

This change:
1. Adds a couple of links directly to the demo.
2. Correctly moves the **Theme Customization** section in the README.

chore: minor tweaks and pointers to demo

---

supabase/migrations/20230405074631_customers.sql

Adding the local migration for the customer table.

chore: add customer table migration.

---

components/Dashboard.tsx
routes/index.tsx

This change:
1. Adds a footer to the dashboard pages.
2. Removes links to sections of the homepage.
3. Adds the "Made with Fresh" badge to the footer.

refactor: footer improvements

---

.gitignore
deno.json

Reason: https://github.com/denoland/deno-gfm/issues/47#issuecomment-1460872019

refactor: disable lock

---

utils/supabase_types.ts
utils/todos.ts

Previously, `deno check main.ts` was failing. Now, it's not.

fix: supabase types

---

deno.json

Closes #23. Thanks to esm-dev/esm.sh#572.

fix: remove `--cached-only` flag from `start` task

---

routes/api/login.ts
routes/api/signup.ts
routes/login/index.tsx
routes/signup.tsx

This PR:
1. Fixes #52 and #48.
2. Applies the same fix to the login page for future use.
3. Includes design reasoning in the JSDoc.
4. Adds a bottom margin to the `<Notice />` component on these pages.

fix: improve auth error message handling

---

fresh.gen.ts
import_map.json
routes/feed.ts

feat: add blog RSS feed

---

routes/login/index.tsx

fix: `/login` should redirect if user is logged in

---

components/OAuthLoginButton.tsx
routes/index.tsx

It appears to have come from #89.

fix: `<OAuthLoginButton />` and `<PricingCard />` style regressions

---

README.md

This seems like a more appropriate location for the section.

docs: move global constants docs

---

components/OAuthLoginButton.tsx

fix OAuth button turning completely black when hover

fix: oauth button style regression

---

components/AuthForm.tsx
components/Layout.tsx
routes/_404.tsx
routes/_500.tsx
routes/account/index.tsx
routes/blog/[slug].tsx
routes/blog/index.tsx
routes/index.tsx
routes/login/index.tsx
routes/signup.tsx
routes/submit.tsx
utils/constants.ts

refactor: remove `BASE_` prefix from constants names

---

components/OAuthLoginButton.tsx

revert: re-enable OAuth

---

routes/_middleware.ts

This fixes the current CI issue.

fix: `supabaseClient` state type

---

README.md
fresh.gen.ts
islands/AuthFragmentCatcher.tsx
routes/account/index.tsx
routes/account/reset-password.tsx
routes/forgot-password.tsx
routes/login/index.tsx
routes/login/success.tsx

Able to take a look, @thorwebdev?
Todo:
Supersedes #105.

feat: password reset flow

---

components/ItemSummary.tsx
routes/account/index.tsx
routes/item/[id].tsx
utils/db.ts

I should've included this in #144.

feat: `getUserDisplayName()`

---

fresh.gen.ts
routes/account/display-name.tsx
routes/account/index.tsx
utils/db.ts

Now, users can update their display names.

feat: change display name

---

routes/account/display-name.tsx

This fixes the HTTP code 405 error when changing display user name.

fix: HTTP redirect status code

---

components/ItemSummary.tsx

feat: Deno Hunt premium user "tick"

---

routes/account/index.tsx
routes/index.tsx
routes/item/[id].tsx

refactor: remove dividers

---

routes/account/upgrade.ts
utils/db.ts

close https://github.com/denoland/saaskit/issues/172

fix: fail to upvote others posts

---

components/Layout.tsx
routes/account/display-name.tsx
routes/account/index.tsx
routes/account/reset-password.tsx
routes/blog/[slug].tsx
routes/blog/index.tsx
routes/forgot-password.tsx
routes/index.tsx
routes/item/[id].tsx
routes/login/index.tsx
routes/signup.tsx
utils/constants.ts

This improves the layout on smaller screens.

refactor: adjust site-wide spacings

---

.github/workflows/ci.yml
.github/workflows/lighthouse.yml

feat: lighthouse in CI

---

.example.env

Fixes #167. For context, see https://github.com/denoland/saaskit/issues/167#issuecomment-1546857460.
FYI, @cdoremus and @lambtron.

fix: type error on setup

---

utils/db.ts

fix: Cannot read properties of null

---

islands/VoteButton.tsx

close https://github.com/denoland/saaskit/issues/199

fix: showing negative vote count

---

routes/account/_middleware.ts

close https://github.com/denoland/saaskit/issues/206

fix: cannot read properties of undefined (reading 'isSubscribed') on account page

---

islands/VoteButton.tsx
routes/index.tsx

close https://github.com/denoland/saaskit/issues/215
close https://github.com/denoland/saaskit/issues/216

fix: upvote malfunction

---

utils/db.ts
utils/db_test.ts

Addresses https://github.com/denoland/saaskit/pull/221#issuecomment-1558526168

refactor: move `deleteUser()` to test file

---

components/UserPostedAt.tsx
fresh.gen.ts
routes/user/[username].tsx
utils/db.ts

https://github.com/denoland/saaskit/issues/181

feat: user pages

---

main.ts
tools/migrate_kv.ts

chore: migrate KV temporary tool

---

routes/index.tsx
tools/migrate_kv.ts

This is a prerequisite for #241.
Please review, @huai-jie.

fix: migrate KV data for #241

---

islands/VoteButton.tsx
routes/index.tsx
routes/stats.tsx
utils/db.ts
utils/db_test.ts

close https://github.com/denoland/saaskit/issues/240

fix: incorrect month of visits

---

tools/migrate_kv.ts

Fixes #245.
Please review, @brunocorrea23.

fix: migrate KV for #245

---

tools/dump_kv.ts

Fixes #262 by adding an extensible `replacer` function that handles `BigInt` values correctly

fix: bigint serialization error

---

islands/VoteButton.tsx

This PR fixes #270 by redirecting to the correct `endpoint`

fix: redirect to correct endpoint

---

routes/stats.tsx

feat: make charts start at 0

---

twind.config.ts

Follow up to #282.
CC @lino-levan

chore: add note about `presetAutoprefix()` removal

---

routes/item/[id].tsx
utils/db.ts
utils/db_test.ts

refactor: comment logic in KV

---

.gitignore
components/Head.tsx
islands/VoteButton.tsx
routes/submit.tsx

- removes unused imports
- adds webstorm .idea dir to gitignore

chore: cleanups and ignore `.idea` folder

---

components/PageSelector.tsx
fresh.gen.ts
islands/PageInput.tsx

fix: page input doesn't submit upon change

---

utils/db_test.ts

chore: improve coverage around `voteCount`

---

routes/item/[id].tsx

fix: comment input width

---

routes/stats.tsx

This change cleans up some code and some visual aspects of the design.

refactor: tweak visual design of `/stats` page

---

routes/_middleware.ts
routes/index.tsx

This is a more accurate measurement of requests to the site.

refactor: move `incrVisitsCountByDay()` to site middleware

---

components/Footer.tsx
components/Header.tsx

fix: links do not have a discernible name

---

components/Header.tsx
e2e_test.ts
routes/_middleware.ts
routes/signin.ts

Now, site middleware isn't as messy.

refactor: cleanup middleware

---

components/Meta.tsx
routes/_app.tsx
routes/blog/index.tsx

This also adds a meta description to all pages.

refactor: simplify `<Meta />`

---

components/Header.tsx

Targets #335 
I added the relative tag on the Header.tsx page, but could also have added it 'globally' on the LINK_STYLES on the constants.ts file.
WDYT?

fix: notification dot position

---

deno.json
routes/blog/[slug].tsx

Also updates [gfm](https://deno.land/x/gfm).
Closes #301

fix: blog dark theme styling

---

deno.json
fresh.gen.ts
islands/Chart.tsx
islands/LineChart.tsx
routes/stats.tsx

this pr adds a first version of a chartjs island as seen in the draft in `fresh_charts`:
https://github.com/denoland/fresh_charts/pull/15

feat: add first working draft of Chart.js islands

---

components/Icons.tsx
routes/pricing.tsx
tools/init_stripe.ts
twind.config.ts
utils/payments.ts

fix(frontend): redesign pricing

---

routes/item/[id].tsx

fix: user triggers own notifications

---

README.md

fix: correct description in README

---

components/Header.tsx
routes/submit.tsx

refactor: add spice to submit buttons

---

data/posts/second-post.md
e2e_test.ts
routes/feed.ts
utils/posts_test.ts

fix: feed and add test

---

components/Head.tsx
routes/_app.tsx
routes/account/index.tsx
routes/account/notifications.tsx
routes/blog/[slug].tsx
routes/blog/index.tsx
routes/index.tsx
routes/item/[id].tsx
routes/pricing.tsx
routes/stats.tsx
routes/submit.tsx
routes/user/[username].tsx

Managing the title via state was cumbersome. This change enables the upgrade to Fresh v1.3.

refactor: re-introduce `<Head />`

---

deno.json

Tests are already fast. But this change makes them faster.

chore: parallel tests

---

components/UserPostedAt.tsx

This will bring the "Best Practices" score from 92 to 100. #268

fix: avatar resolution

---

components/Footer.tsx
e2e_test.ts
fresh.gen.ts
routes/dashboard/_middleware.ts
routes/dashboard/stats.tsx

feat: stats behind auth

---

components/Icons.tsx
routes/submit.tsx

Hash: I feel like this is missing something, but I don't know what. Any ideas, or do you think it's good?
Andy: I included minimal copy, which looks sufficient to me.
Before:
After:

refactor: redesign submit page

---

tools/migrate_kv.ts
utils/db.ts

This change cleans up some of the user-related data in KV.
Closes #412

fix: user not found

---

fresh.gen.ts
islands/UsersTable.tsx
routes/dashboard/users.tsx

feat: cursor-based pagination for users table

---

routes/submit/index.tsx

fix: submit route import

---

deno.json
e2e_test.ts
islands/ItemsList.tsx
routes/_middleware.ts
routes/account/index.tsx
routes/callback.ts
routes/signin.ts
routes/signout.ts
utils/middleware.ts
utils/redirect.ts
utils/redirect_test.ts

This also includes some related cleanups and fixes.

chore: upgrade to deno_kv_oauth@0.5.0

---

islands/CommentsList.tsx
islands/ItemsList.tsx
islands/NotificationsList.tsx
islands/UsersTable.tsx
utils/constants.ts

This change changes the text to "Loading..." once the button is clicked instead of disappearing. It also prevents the button from actioning anything while in the loading state.

refactor: improve "Load more" button design

---

components/Footer.tsx
utils/constants.ts
utils/display.ts
utils/display_test.ts

It didn't seem all that useful.

refactor: remove `getToggledStyles()`

---

CONTRIBUTING.md

The aim of this change is to make contributions clearer to approach.

docs: improve contributing guide

---

README.md

As we've closed the roadmap issue.

chore: remove roadmap reference

---

e2e_test.ts
routes/api/items/index.ts
routes/submit.tsx

refactor: move `POST /submit` to `POST /api/items`

---

utils/db.ts

refactor: remove `getValue()`

---

e2e_test.ts
fresh.gen.ts
routes/api/comments.ts
routes/api/items/[id]/comments.ts
routes/items/[id].tsx

refactor: move `POST /items/[id]` to `POST /api/comments`

---

e2e_test.ts
utils/db_test.ts
utils/display_test.ts
utils/http_test.ts
utils/posts_test.ts

chore: update assertion imports

---

e2e_test.ts

chore: flatten e2e tests

---

routes/items/[id].tsx
utils/constants.ts

chore: disable comments unless user is signed in

---

deno.json

chore: upgrade to Fresh 1.4.3

---

README.md

docs: "Deploy to Production" cleanups

---

utils/http.ts

docs: complete JSDocs for `utils/http.ts`

---

components/Share.tsx

This change applies `encodeURIComponent()` to the dynamic parts of the share URLs.

fix: encode URI components

---

routes/api/items/[id]/vote.ts
utils/db.ts
utils/db_test.ts

chore: add testing and JSDocs to voting logic

---

routes/notifications/[id].ts
utils/db.ts
utils/db_test.ts

This change replaces `getNotification()` and `deleteNotification()` with `getAndDeleteNotification()`, which is atomic.

refactor: `getAndDeleteNotification()`

---

plugins/kv_oauth.ts
plugins/kv_oauth_test.ts

chore: add `getGitHubUser()` JSDocs and test

---

e2e_test.ts
routes/api/stripe-webhooks.ts

Towards https://github.com/denoland/saaskit/issues/267 and https://github.com/denoland/saaskit/issues/492

chore: add `POST /api/stripe-webhooks` catches and tests

---

islands/NotificationsList.tsx

Closes #467
CC @brunocorrea23
Before:
After:

refactor: tweak `<NotificationsList />` design

---

routes/users/[login].tsx

fix(profile): apply 2 column layout to Profile page

---

plugins/kv_oauth.ts
tasks/db_seed.ts
utils/db.ts
utils/db_test.ts

refactor: improve and document users logic

---

components/ItemSummary.tsx

This will probably help with SEO.

refactor: `after:content` for new window symbol

---

e2e_test.ts
utils/display.ts
utils/display_test.ts

Adding more e2e coverage for #524

chore: adds e2e tests for `POST /api/comments`

---

.github/codecov.yml

See https://github.com/denoland/saaskit/pull/557#issuecomment-1712898309

refactor: expand test coverage to `/routes`

---

e2e_test.ts

chore: add `GET /api/me/votes` test

---

routes/index.tsx
routes/items/[id].tsx
routes/users/[login].tsx

feat: fetch preload `GET /api/me/votes` when user is signed in

---

routes/api/comments.ts
utils/db.ts
utils/db_test.ts

refactor: move notification logic into `createComment()`

---

tasks/db_seed.ts

See https://github.com/denoland/saaskit/issues/588

fix: prevent duplicate users in seed task

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
deno.json
plugins/kv_oauth.ts

See https://github.com/denoland/deno_kv_oauth/releases/tag/v0.7.0

chore: update to `deno_kv_oauth@v0.7.0`

---

routes/account/index.tsx

fix: account page spacing

---

routes/account/index.tsx
utils/constants.ts

This change adds a "Go to my profile" link and changes the styling and positions of links on the account page.

refactor: account page tweaks

---

e2e_test.ts

chore: further tidy e2e tests

---

e2e_test.ts
islands/ItemsList.tsx
routes/api/items/[id]/vote.ts
utils/db.ts
utils/db_test.ts

This makes votes immutable, like Hacker News. This provides the benefit of greatly simplifying related logic.

refactor: remove vote deletion functionality

---

tasks/db_restore.ts
utils/db.ts

Fixes various minor JSDoc snippet issues.

fix: correct JSDoc snippets

---

plugins/kv_oauth.ts
utils/db.ts
utils/db_test.ts

Now, updating a user's session ID happens within a single atomic operation.

refactor: update user session in a single atomic operation

---

main.ts

This console message directs the dev to where they can learn to set up Stripe.

chore: improve Stripe disabled message

---

routes/pricing.tsx

This points the web dev to the appropriate README section for creating a Stripe product.

refactor: improve Stripe product setup warning

---

components/Footer.tsx
components/Header.tsx
utils/constants.ts

refactor: use Fresh's active link styling

---

tasks/db_dump.ts
utils/db.ts
utils/posts.ts

Revert "refactor: use `Array.fromAsync()`"

---

tasks/db_dump.ts
utils/db.ts
utils/posts.ts

IIUC, `Array.fromAsync()` is now supported.
Reverts denoland/saaskit#643

Revert "Revert "refactor: use `Array.fromAsync()`""

---

components/Meta.tsx

As pointed out in https://github.com/denoland/saaskit/commit/14a991f380020fc0c1c4976176de226eb982cef0#commitcomment-137941513

chore: remove redundant meta tag

---

routes/pricing.tsx

fix: correct typo on the pricing demo page

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
components/Header.tsx
components/PremiumBadge.tsx
islands/ItemsList.tsx
islands/UsersTable.tsx
plugins/blog/routes/blog/[slug].tsx
plugins/blog/routes/blog/index.tsx
routes/pricing.tsx
routes/submit.tsx

chore: update for Deno 2

---

components/Footer.tsx
islands/ItemsList.tsx
plugins/blog/components/Share.tsx
routes/users/[login].tsx

- #696 Add rel attribute to external links.
- Replaced inline props with interface for better consistency.

fix: add rel for external links
