README.md

When not setting `STRIPE_PREMIUM_PLAN_PRICE_ID` to one's own id Stripe will not be able to find the product. This will fail with a 500 error.
Fixes #7

docs: clarify premium price id in `constants.ts`

---

components/Dashboard.tsx
components/Nav.tsx

This PR improves the semantics of `nav` elements to be "more correct", according to [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav#examples).

refactor: improve nav element semantics

---

components/Input.tsx
islands/TodoList.tsx

Previously, the `TodoList` island used a signal for reading and writing (resetting to blank) the value of the `input` element containing the `newTodo.name` value. The value of this signal was updated every time there was a keystroke in the input.
Now, thanks to [`useRef`](https://preactjs.com/guide/v10/hooks/#useref), the value of the input is only read and reset upon submission of the form. This required a refactor of the `Input` component to use [`forwardRef`](https://preactjs.com/guide/v10/switching-to-preact#forwardref).

refactor: `useRef` in `TodoList` island

---

utils/stripe.ts

Previously, preview deployments would fail because the `STRIPE_SECRET_KEY` environment variable couldn't be read as part of a limitation of Deno Deploy.
Now, a dummy Stripe secret key is used as a fallback, so preview deployments work to a certain extent. Any pages needing to use the `stripe` instance won't work.

fix: dummy Stripe API key

---

routes/dashboard/_middleware.ts
routes/dashboard/account.tsx
routes/dashboard/manage-subscription.ts
routes/dashboard/todos.tsx
routes/dashboard/upgrade-subscription.ts

Previously, `createOrGetCustomer()` was called every time a `/dashboard/**` request was made.
Now, `createOrGetCustomer()` to the `/dashboard` middleware context so it can be called only when needed.
Ref:
* https://github.com/denoland/saaskit/pull/16#discussion_r1154137671

refactor: `createOrGetCustomer()` in middleware state

---

routes/blog/[slug].tsx
routes/blog/index.tsx

This PR adds a footer to the `/blog` and `/blog/<slug>` pages. For this I used the nav links already used on the landing page. 
Fix #29

feat: add general footer to blog pages

---

routes/index.tsx

fix: pricing image sizing

---

README.md

This change updates the roadmap URL to the new pinned issue instead of the GitHub project.

docs: update roadmap reference

---

routes/dashboard/_middleware.ts

This change removes an unneeded assertion and `getLoginPath()`. This assertion was seemed misleading as having a nully `session` object isn't an error.

fix: unneeded assertion and cleanup

---

components/Head.tsx
components/Meta.tsx
routes/blog/[slug].tsx
routes/blog/index.tsx
routes/index.tsx

This fixes #55. 
I added the newly created `Meta` component also to the `Head` component which is already used on a couple of pages. 
Happy to about any feedback about the component.

feat: meta tag component

---

README.md
deno.json
dev.ts
init/stripe.ts

Previously, a bit of manual work was required to set up Stripe. This change adds the init:stripe task, which:
1. Automatically creates the "Premium tier" product.
2. Automatically creates the default billing portal configuration used in the /dashboard/manage-subscription route.
3. Prints the "Premium tier" product price ID to be copied into constants.ts.
This dramatically reduces the time and steps needed and the chance of errors in setting up Stripe.
Contributors, please feel free to test and provide feedback.

feat: `deno task init:stripe` and further documentation improvements

---

README.md

This change renames "Extending Deno SaaSKit" to "Customization" and moves it to a more appropriate location (in between "Getting Started Locally" and "Deploying to Production").
Other documentation tweaks have also been made.

docs: "Customization" section and further tweaks

---

README.md

See #75. These may be added back one day, but only once they've been flushed out. Either way, the aspects are tracked in the PR.
Towards #70.

docs: remove "Architecture" section

---

routes/account/index.tsx

The account page is no longer part of the dashboard, so it's design can be simplified.
This is a prerequisite for the upcoming dynamic header design.

refactor: redesign account page

---

components/Layout.tsx

feat: Deno Hunt beta site banner

---

routes/signup.tsx

Now, a response is returned early once an error is detected.

fix: signup error handling

---

components/OAuthLoginButton.tsx
routes/login/index.tsx
routes/signup.tsx

The OAuth button is disabled on local machines and enabled everywhere else. Some changes have been made in Supabase also.

fix: re-enable OAuth

---

routes/_middleware.ts

Now, the top-level middleware doesn't process routes whose pathnames include `_frsh`, `.ico` or `logo`.

fix: filter middleware routes

---

routes/_middleware.ts
routes/logout.ts

Previously, the middleware filter was skipping on populating state for the logout route. This was because "logo", which was for the site logo, mistakenly added the **logo**ut route to the skip list.
This change ensures the `ctx.state` object is populated in the logout route and dynamically sets the skip list by whether the incoming request is a Fresh keepalive or static file request.

fix/refactor: improve middleware filter

---

components/ItemSummary.tsx
routes/_middleware.ts
routes/account/index.tsx
routes/account/manage.ts
routes/account/upgrade.ts
routes/api/stripe-webhooks.ts
routes/index.tsx
routes/item/[id].tsx
utils/db.ts

This change:
* Simplifies how database objects are get and set by including the `id` property in the respective object. This means we can return the object's value, including the `id`, ignoring the key.
* Re-introduces `getOrCreateUser()`, which ensures a user object always exists. This is particularly valuable for OAuth users.
Fixes:
* #133

fix/refactor: simplify db types and re-introduce `getOrCreateUser()`

---

components/OAuthLoginButton.tsx

This change re-enables OAuth for preview and production deployments. This action was previously blocked by #133.
A further PR will enable OAuth for local development.
This has been tested and is working on the preview deployment.

feat: re-enable OAuth

---

routes/submit.tsx

Now, the user is redirected to the item page once the item is created.

feat: redirect to item page after submission

---

routes/index.tsx
utils/db.ts

This will either fix the current server-side error or help in diagnosing it.
```
An error occurred during route handling or page rendering. TypeError: Error parsing args at position 2: expected string, number, bigint, ArrayBufferView, boolean
at Object.opAsync (ext:core/01_core.js:256:30)
at KvListIterator.<anonymous> (ext:deno_kv/01_db.ts:107:42)
at KvListIterator.next (ext:deno_kv/01_db.ts:379:48)
at getItemCommentsCountsByIds (file:///src/utils/db.ts:105:26)
at eventLoopTick (ext:core/01_core.js:165:11)
at async GET (file:///src/routes/index.tsx:11:32)
at async https://deno.land/x/rutt@0.1.0/mod.ts:143:36
at async handler (file:///src/routes/_middleware.ts:26:22)
at async Server.handler (https://deno.land/x/fresh@1.1.5/src/server/context.ts:220:25)
at async Server.#respond …
```

refactor: simplify commentsCount logic

---

tools/reset_kv.ts

This will be useful for running one-off database data resets in deployment.

feat: export `resetKv()`

---

main.ts
tools/reset_kv.ts

Due to recent database changes, this must be run once in preview and production deployments.

chore: one-time data reset

---

twind.config.ts

This fixes current type-checking failures. This is a band-aid fix and should be fully looked into at some point.

fix: tailwind option types

---

components/Layout.tsx
routes/_middleware.ts
routes/account/index.tsx
routes/blog/[slug].tsx
routes/blog/index.tsx
routes/index.tsx
routes/item/[id].tsx
routes/submit.tsx

`Session | null` has the same effect and is already present in the same places that `isLoggedIn` was. This is one less moving part.

refactor: remove `isLoggedIn` property

---

routes/index.tsx

It seems as though `Deno.Kv.getMany()` has a limit of 10 entries. This appears to be a hard limit independent of consistency level. This will need to be investigated further and may require pagination in the future.

fix: limit feed to 10 items

---

routes/index.tsx

This should've been done in #162.

refactor: use of `getAllItems()`

---

.github/workflows/ci.yml

This ensures consistency between CI and local machines. My only concern is that we'll lose some debugability if something fails in CI. We'll have to see.

refactor: use `deno task ok` task in CI

---

deno.json

This change provides the necessary `--allow-write` permission to the `check:license` task, which is needed when not using the `--check` flag.

fix: `deno task check:license` permissions

---

README.md

This change makes local development quieter by only listening to Stripe events we care about.

docs: filter Stripe events for `listen` command

---

components/ItemSummary.tsx
import_map.json
routes/index.tsx
routes/item/[id].tsx
utils/db.ts

This change removes the comments part of `<ItemSummary />`. [Previously](https://github.com/denoland/saaskit/pull/137), this was argued to be a good indicator of an interesting item. However, with the complexity and computational cost of such a minor feature and the onset of voting functionality, it's more reasonable not to have the feature. A vote score is a sufficient indicator of an item's value.
However, an item's comment count can still be seen on the item page, which is calculated without an extra database call through `comments.length`. A few other adjustments had to be made to make `<ItemSummary />` usable:
1. The item title now links to the item page.
2. The item URL host now links to the item URL in a new tab, with a symbol included to indicate so.
3. Both new links get …

refactor: remove comments count

---

routes/account/upgrade.ts

According to the documentation, it's fine to use the non-null assertion error on `url` as the session is active in our case.
> The URL to the Checkout Session. Redirect customers to this URL to take them to Checkout. If you're using Custom Domains, the URL will use your subdomain. Otherwise, it'll use checkout.stripe.com. This value is only present when the session is active.
Fixes #179.

fix: Stripe checkout session type error

---

utils/auth.ts

Since Supabase is now only used for authentication, the `responseHeaders` parameter is always provided. Hence, it's no longer optional.

refactor: minor cleanup of `createServerSupabaseClient()`

---

routes/_middleware.ts

Supabase client sets two cookies during logout:
```
set-cookie supabase-auth-token=; SameSite=Lax; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
set-cookie supabase-auth-token-code-verifier=; SameSite=Lax; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
```
Previously, with `set` method the first cookie was not returned to the browser.
Fixes #153

Append cookies in the response from supabase

---

.github/dependabot.yml

This weekly action ensures other GitHub actions are kept up-to-date. See [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) for more info.

feat(ci): dependabot for GitHub actions

---

main.ts

This temporary switch triggers a Deno KV reset when `RESET_DENO_KV = "1"`. This will be removed once the KV has stabilised.

chore: add internal reset KV trigger

---

routes/item/[id].tsx

Currently the comment box is at the bottom of the page, which isn't very intuitive. This PR just moves it to the top.

fix: move comment box to top

---

components/ItemSummary.tsx
components/UserPostedAt.tsx
routes/item/[id].tsx
utils/display.ts
utils/display_test.ts

This change brings consistency between `<ItemSummary />` and item comments. It also moves `pluralize()` and `timeAgo()` to `/utils/display.ts`.
Prerequisite for #222.

feat: `<UserPostedAt />`

---

routes/api/stripe-webhooks.ts
routes/api/vote.ts
routes/callback.ts
routes/index.tsx
routes/item/[id].tsx
routes/user/[username].tsx
utils/db.ts
utils/db_test.ts

This PR:
1. Introduces page-number-based pagination to the homepage.
2. Refactors much of the database-related code to be more straightforward.
3. Changes the homepage to show only the items posted in the last week.
4. Supercedes #236
5. Moves functionality closer to #211
6. Closes #233
7. Closes #231
Note: once merged, these same changes can be made to paginate item and user pages.
Please feel free to review, @brunocorrea23 and @huai-jie.

feat: page-number-based pagination

---

README.md

Fixes a few things in read.
See the updated readme [here](https://github.com/baqirkhan/saaskit/tree/baqir/update-readme).

docs: fix README spacing and numbering

---

routes/index.tsx
routes/stats.tsx
utils/db.ts

- Refactored the code a little bit to make it very easy to add new stats
- Added missing stats from #202 (New items per day, New votes per day, New users per day)
- Changed the kv key for the 'visits per day' stats. Means we would lose the data we had before if there is no migration.
- UI for the /stats page needs some love
- Does not address #240 as it should be solved in #241

feat: adding new stats

---

.github/codecov.yml
.github/workflows/ci.yml
.gitignore
deno.json

chore: setup Codecov

---

components/UserPostedAt.tsx

after the previous PR #277 , lighthouse started complaining about low resolution of the avatar images. I'm increasing the size from 24 to 36 and it should solve this issue.

fix: avatar size

---

deno.json
twind.config.ts

Everything appears fine after the changes.

refactor: cleanup `twind`-related functionality

---

routes/api/vote.ts
routes/index.tsx
routes/item/[id].tsx
routes/submit.tsx
routes/user/[username].tsx
tools/seed_submissions.ts
utils/db.ts
utils/db_test.ts

Before, functions within `util/db.ts` did too much. E.g. `createItem()` generated an item, set it in KV, and then returned the generated item. Now, functions only do one thing, making things easier to understand and maintain.
This is part 1 of a series of PRs that simplifies DB/KV logic. This part focuses on items specifically.
Towards #267

refactor: items logic in KV

---

routes/index.tsx

After the refactor, the default timeAgo selector is set for all time.
This PR changes it back to the week being the default.

fix: default timeAgo

---

routes/blog/[slug].tsx
routes/blog/index.tsx

At the moment the blog is not readable since it has css classes set only for a light theme. Since SaaSKit changed to support both light and dark themes the blog also needs to support that. This fixes the CSS on the SaaSKit side. However since we use `deno-gfm` we might think about adding our own CSS to for the rendered markdown files.

fix(blog): respect user theme choice

---

data/posts/second-post.md
routes/blog/[slug].tsx
utils/db_test.ts
utils/posts.ts
utils/posts_test.ts

this pr attempts to improve the coverage as mentioned in #267.  
to reduce the boilerplate on writing further tests, a couple `genNew<Entity>` functions have been created.  
these helper functions are now used for all tests cases, if applicable.

test(utils): further improve test coverage

---

utils/db_test.ts

This change increases the tolerance of instances of `assertAlmostEquals()` by order of magnitude. Previously, this was causing CI failures.

fix: `assertAlmostEquals()` tolerance in tests

---

routes/_middleware.ts

The new home for Deno Hunt is now https://hunt.deno.land

feat: redirect to new host

---

utils/db.ts
utils/db_test.ts

feat: `deleteItem()` and `deleteComment()`

---

tools/migrate_kv.ts

chore: delete dummy data

---

routes/callback.ts
routes/index.tsx
routes/submit.tsx
utils/db.ts
utils/db_test.ts

refactor: analytics into atomic operations

---

routes/stats.tsx
utils/db.ts
utils/db_test.ts

Previously, the analytics-related functions in `@/utils/db.ts` did too much. This PR simplifies these functions. I also chose not to hardcode the specific metric value and instead it be a function argument.
PTAL, @brunocorrea23 and @mbhrznr.
Pre-requisite for #289

refactor: simplify analytics-KV data

---

tools/seed_submissions.ts

`incrementAnalyticsMetricPerDay` does not exist anymore in `db.ts`.
This pull request just remove invalid imports.
When I ran the `db:seed` task during `saaskit` startup, I got an error, and this pull request was enough to get rid of it.

fix: remove deprecated `incrementAnalyticsMetricPerDay()`

---

routes/stats.tsx
utils/db.ts
utils/db_test.ts

closes #276.
sets the y-axis' ticks to be of natural numbers.
populates the x-axis with sequential dates.
to prevent us from having "holes" in the retrieved dates, a new `getDatesSince` has been introduced.
the returned array can then can be used to query the necessary fields from our analytics stores.

fix(stats): populate empty chart axis

---

routes/stats.tsx

This change improves how the charts on mobile screens are displayed by wrapping each chart in a `<div>` with `overflow: auto` styling.

fix: stats graphs on mobile screens

---

deno.json
routes/stats.tsx

This change horizontally aligns graphs to the centre of the page on desktop screens.
This is a follow-up to #319
Depends on https://github.com/denoland/fresh_charts/pull/14
CC @kt3k

fix: stats graphs alignments

---

routes/user/[username].tsx

feat: pagination for authors page

---

components/Layout.tsx
deno.json
routes/account/manage.ts
routes/api/stripe-webhooks.ts
routes/pricing.tsx
stripe.ts
utils/payments.ts

Fixes https://github.com/denoland/saaskit/issues/261
I started by adding
```
// @deno-types="npm:stripe"
```
just above the `Stripe` import.
This is based on https://deno.com/manual@v1.34.0/advanced/typescript/types#providing-types-when-importing
This is not the best solution, but currently there's an issue with having types for Stripe in Deno: 
https://github.com/stripe-samples/stripe-node-deno-samples/issues/2
After the initial error was fixed, I was receiving a different error, also caused by type assertions, so I had to change
```
pricePerInterval={toPricePerInterval(
product.default_price as Stripe.Price,
)}
```
and handle all cases
1. `git clone ...`
2. `deno task start`
3. access http://localhost:8000/pricing
4. you shouldn't see a 500 error
`defaultPrice.recurring?.interval` …

fix: Stripe types and checks

---

utils/db.ts

Please review, @brunocorrea23.

perf: improve `ifUserHasNotifications()`

---

islands/Chart.tsx
routes/stats.tsx

This change:
* Simplifies the `<Chart />` island to only return the `<canvas>` element. Parent styling can be done separately.
* Combines 4 charts into a single, large, interactive chart that can hide/show datasets.
* Adds enables the [`index`](https://www.chartjs.org/docs/latest/samples/tooltip/content.html) interaction mode, which shows the values for all shown datasets for a given date.
* Removes configuration and code which may not be needed.
* Disables `maintainAspectRatio`.
Please review by checking deployment, @mbhrznr.

refactor: stats charts improvements and simplifications

---

deno.json

I just realised that this might be the cause of our woes. Previously, the target would've been `deno` as islands are built server-side. Checkout "ESBuild Options" in https://esm.sh/#docs 
Closes #354
Supercedes #355

fix: target `es2022` for `Chart.js` import and upgrade to v4.3.0

---

routes/user/[username].tsx

This closes #347. 
I added the GitHub icon right next to the user's name with our `LINK_STYLES`.

feat: add GitHub profile to user's page

---

tools/migrate_kv.ts

This chore removes more dummy data from the KV store. To Deno Hunt users, we're soon launching v1. We'd appreciate if test and dummy posts are no longer shared.
FYI @lambtron

chore: cleanup KV

---

utils/db_test.ts

Previously, `assertAlmostEquals()` was causing tests to flake. Using `asserts()` still provides an accurate test for expected behaviour without extraneous precision.

refactor: remove use of `assertAlmostEquals()`

---

components/GitHubAvatarImg.tsx
components/UserPostedAt.tsx
routes/account/index.tsx
routes/callback.ts
routes/user/[username].tsx
tools/migrate_kv.ts
tools/seed_submissions.ts
utils/db.ts
utils/db_test.ts

This change adds a new size-adjustable and class-customisable `<GitHubAvatarImg />`. It's dynamically generated using the user's login (AKA username). As a result, the `avatarUrl` property from the `User` interface has been removed.
The migration script updates all user objects without the `avatarUrl` property.
Please review, if you'd like, @brunocorrea23.

feat: `<GitHubAvatarImg />`

---

fresh.gen.ts
routes/user/[login].tsx

This is more consistent with how GitHub names the property.

refactor: rename user page param to `login`

---

components/ItemSummary.tsx
components/UserPostedAt.tsx
routes/item/[id].tsx
routes/user/[login].tsx

This change moved the premium badge from being shown in item and comment rows to only on user pages. This is part of a move towards removing the `id` field from the `User` interface.

refactor: move premium user badge

---

routes/item/[id].tsx
tools/migrate_kv.ts
utils/db.ts
utils/db_test.ts

This change replaces the `userId` property on the `Comment` interface with `userLogin`. The benefit of this is that we eliminate KV-flavoured joins from DB logic, making it much more straightforward.
This is part of a series of PRs moving towards removing the `User["id"]` property from the codebase. Reviewers, please pay close attention to the migration script, which migrates the old comment interface to the new one.
CC @brunocorrea23, @mbhrznr

refactor: use `userLogin` property in `Comment` interface

---

routes/account/_middleware.ts
routes/account/index.tsx
routes/account/manage.ts
routes/account/notifications.tsx
routes/account/upgrade.ts
routes/dashboard/_middleware.ts
routes/dashboard/stats.tsx
utils/middleware.ts

This will make future protected routes easier to implement.

feat: `ensureSignedInMiddleware()`

---

tools/migrate_kv.ts
utils/db.ts

The `notifications_by_time` key doesn't appear to be used anywhere.
PTAL, @brunocorrea23.

refactor: remove `notifications_by_time` key use

---

fresh.gen.ts
routes/notifications/[id].ts
routes/notifications/index.tsx

This change simplifies the logic around the notifications page and makes it less hacky. A few styling changes have also been made.

refactor: rework notifications pages

---

components/Share.tsx
routes/blog/[slug].tsx

This component dynamically generates links for sharing the current content on the major social media platforms.

feat: `<Share />`

---

components/TabsBar.tsx
routes/index.tsx

I like TabsBar style that we're using on the dashboard, so I replaced with it.
It looks different from Header Nav, and I think the selection state is easy to see. wdyt?
Before: 
After:

fix: use TabsBar style at TimeSelector

---

components/Icons.tsx
routes/index.tsx

This PR adds empty states to the project list, it guides new users after a fresh install.

fix: add an empty state to the project list

---

components/Icons.tsx
routes/index.tsx

Just an idea, how about issuing an instruction when `GITHUB_CLIENT_ID` and `GITHUB_CLIENT_SECRET` are not set? I think It reduces the feeling of emptyness after initial setup, and it will prevent users from getting lost in both the local environment and the Deno Deploy environment.
If these environment variables are not required, I think this PR is not appropriate and should be closed.
Feel free to rewrite the text if you like this idea.

doc: add a link to auth setup guide

---

components/ItemSummary.tsx
routes/_404.tsx
routes/_500.tsx
routes/_middleware.ts
routes/api/vote.ts
routes/callback.ts
routes/index.tsx
routes/item/[id].tsx
routes/notifications/index.tsx
routes/submit.tsx
routes/user/[login].tsx
tools/migrate_kv.ts
tools/seed_submissions.ts
utils/db.ts
utils/db_test.ts

Vote logic was challenging to deal with, hence the rework. The most involved part of this PR is the migration script. In summary:
* All notifications will be deleted, which, IMO, is ok.
* User entries are untouched.
* Items and votes entries are migrated according to their new respective interfaces.
Reviews, please pay close attention to the migration script. It aims to preserve item, vote and user data. This script has worked multiple times on my local machine, but I still want it checked carefully. To test:
1. On the main branch, run `deno task db:reset` and then `deno task db:seed`.
2. Run `deno task start`, sign in, vote and comment on random items, noting the changes.
3. Switch to this branch and run `deno run -A --unstable tools/migrate_kv.ts`.
4. Run `deno task start` and ensure …

refactor: remove `user.id` use and rework vote logic

---

e2e_test.ts
fresh.gen.ts
routes/api/users/[login]/index.ts
routes/api/users/[login]/items.ts
routes/api/users/index.ts
utils/db.ts
utils/db_test.ts
utils/pagination.ts

This change adds the following REST API endpoints.
- `GET /api/users`
- `GET /api/users/[login]`
- `GET /api/users/[login]/items`
Documentation will come in a follow-up PR.
Towards #439

feat: REST API for users

---

e2e_test.ts
fresh.gen.ts
routes/api/items/[id]/comments.ts
routes/api/items/[id]/index.ts
routes/api/items/index.ts
tools/migrate_kv.ts
utils/db.ts
utils/db_test.ts

This change adds the following REST API endpoints:
- `GET /api/items`
- `GET /api/items/[id]`
- `GET /api/items/[id]/comments`
Documentation will come in a follow-up PR.
Prerequisite for #438 or #429
Towards #439

feat: REST API for items and comments

---

e2e_test.ts
fresh.gen.ts
islands/NotificationsList.tsx
routes/api/users/[login]/notifications.ts
routes/notifications/index.tsx
tools/migrate_kv.ts
utils/db.ts
utils/db_test.ts

This change adds the `GET /api/users/[login]/notifications` REST API endpoint.
Documentation will come in a follow-up PR.
Towards #439 and #414

feat: REST API and cursor-based pagination for notifications

---

routes/submit/index.tsx
utils/url_validation.ts
utils/url_validation_test.ts

closes #378.  
adds some naive url validations to the submit route.  
adds some tests for these naive validations.
these validations check that:
- the urls start w/ `http:` or `https:`
- the urls don't use local ip addresses and/or `localhost`

feat: add URL validation

---

routes/submit/index.tsx

closes #377.  
this disallows users from submitting duplicate entries.  
upon submission all user entries are checked for uniqueness on either `title` or `url`.

feat: disallow duplicate entries for users

---

e2e_test.ts
fresh.gen.ts
islands/NotificationsList.tsx
routes/api/me/notifications.ts
routes/notifications/index.tsx

From `/api/users/:login/notifications` to `/api/me/notifications`, as the endpoint requires the client to be authenticated.

refactor: move notifications REST API endpoint

---

components/UserPostedAt.tsx
islands/NotificationsList.tsx

This was preventing feeds from being rendered.

fix: `timeAgo()` usage

---

components/UserPostedAt.tsx
islands/CommentsList.tsx
islands/ItemsList.tsx
islands/NotificationsList.tsx
islands/UsersTable.tsx
routes/api/items/[id]/comments.ts
routes/api/items/index.ts
routes/api/me/notifications.ts
routes/api/users/[login]/items.ts
routes/api/users/index.ts
routes/submit/index.tsx
utils/display.ts
utils/display_test.ts
utils/http.ts
utils/http_test.ts
utils/islands.ts
utils/islands_test.ts
utils/pagination.ts

As discussed with @mbhrznr, the duplicate submission posted at a different time hits differently. Also, these validations get in the way when locally testing submissions rapidly. This also includes some other minor fixes and cleanups.

refactor: remove submission validations and island utilities

---

utils/http_test.ts
utils/islands_test.ts

fix: correct `getCursor()` test location

---

islands/ItemsList.tsx
utils/db.ts

Previously, votes weren't getting propagated to the `<VoteButton />` island in time.

fix: `<ItemsList />` fetch resources order

---

.github/codecov.yml

This change expands code coverage from ignoring `/routes`, `/components` and `/islands` to ignoring only `.ts` files. This will give us better visibility into what tests to write, especially for REST API endpoints.

chore: expand test code coverage

---

tasks/db_reset.ts

This cleans up some of the unnecessary LOC for the script.
Related to #471

refactor: cleanup `db:reset` script

---

tasks/db_dump.ts

refactor: simplify `db:dump` task

---

components/Header.tsx

fix: active dashboard link

---

README.md
components/Head.tsx
posts/first-post.md
posts/second-post.md
routes/blog/index.tsx
utils/posts.ts
utils/posts_test.ts

refactor: polish posts tests and documentation

---

routes/pricing.tsx
utils/display.ts
utils/display_test.ts

refactor: complete `utils/display.ts` tests and docs

---

tasks/db_migrate.ts

This change aims to eliminate concurrency in the migration script. Excessive concurrent HTTP requests break the migration process (see https://github.com/seanmonstar/reqwest/issues/976).

fix: `db:migrate` task

---

fresh.config.ts
fresh.gen.ts
plugins/error_handling.ts
plugins/error_handling_test.ts
routes/_middleware.ts
routes/api/_middleware.ts

This plugin centralises error-handling logic across different routes.

refactor: error handling plugin

---

e2e_test.ts
routes/account/manage.ts
routes/account/upgrade.ts
utils/stripe.ts

First contribution towards improving e2e tests in #524

chore: add e2e tests for `GET /account/manage` and `GET /account/upgrade`

---

e2e_test.ts
routes/notifications/[id].ts

Adds coverage as part of #524 
The page can throw a general error, which would happen if the notification was found but then deleting the key in KV failed. I can't think of a great way to exercise this code path unless we mock `getAndDeleteNotification` for one test and have it throw?

chore: add e2e tests for `GET /notifications/[id]`

---

.github/workflows/ci.yml
.gitignore
deno.json

The `cov:view` task generates HTML to view LCOV files using [`genhtml`](https://linux.die.net/man/1/genhtml) and then opens the main page in the local machine's browser. This is good for analysing test coverage locally. The `cov` task has also been renamed to `cov:gen`.

feat: `deno task cov:view`

---

.github/codecov.yml

On second thought, we can make testing web pages a priority after v1.

revert: #560

---

.github/codecov.yml
e2e_test.ts

Adding more coverage on behalf of #524

chore: add e2e tests for `GET /items/:id`, `GET /account`, `GET /dashboard`, `GET /dashboard/stats` and `GET /dashboard/users`

---

islands/ItemsList.tsx

fixes #472 
@iuioiua this is as simple as I got, without being too intrusive; I personally like it; the problem was a bug regarding the state change of the variable `isLoadingSig`, I was able to avoid it by initializing the variable as `undefined` and bypassing it with the conditional rendering not sure if is worth taking another look at it some other time.
Note: The simplicity of this PR does not reflect at all the time that took me to get there — just for the record.

fix: avoid showing "No items found" stats in `<ItemsList />`

---

e2e_test.ts
utils/db_test.ts

Adds coverage on behalf of #524

chore: add e2e tests for `POST /api/items`, `DELETE /api/items/:id/vote` and `POST /api/items/:id/vote`

---

routes/_middleware.ts

Other marketing pages now reference the new home of Deno Hunt, https://hunt.deno.land/.

refactor: remove `redirectToNewOrigin` middleware

---

deno.json

To accompany the `cov:gen` and `cov:view` tasks when working locally.

chore: add `cov:clean` task

---

islands/ItemsList.tsx

A recent database migration means this logic is no longer needed.

chore: cleanup `createdTimeAgo` logic

---

e2e_test.ts
routes/api/items/index.ts
routes/submit.tsx

This change moves the logic for `POST /api/items` to the more appropriate `POST /submit` and adds a simple error message if the form was submitted incorrectly.

refactor: rework submit logic and errors

---

e2e_test.ts
plugins/session.ts
routes/api/items/[id]/vote.ts
routes/submit.tsx

Summary:
* The user is no longer required to be signed in to view the submit page.
* The user still must be signed in to submit (post to `POST /submit`).
* Moved session assertion for `POST /api/items/[id]/vote` and `DELETE /api/items/[id]/vote` to the session plugin.

refactor: rework session logic for submission and voting functionality

---

deno.json
utils/db.ts

This aligns with Deno Deploy's `DENO_KV_ACCESS_TOKEN` environment variable.

refactor: use `DENO_KV_PATH` environment variable

---

utils/db.ts
utils/db_test.ts

This function is not used anywhere in the codebase.

chore: remove `deleteItem()`

---

islands/UsersTable.tsx

fix: premium state in users table

---

islands/ItemsList.tsx
routes/_404.tsx
routes/_500.tsx
routes/index.tsx

It's now a little simpler and the `›` symbol is replaced with the HTML encoded string.

refactor: minor `<EmptyItemsList />` tweaks

---

utils/display.ts

fix: make `formatCurrency()` use `en-US` locale

---

README.md

In this PR, I have fixed the broken link of discord in the README.
Now it redirects to the correct link of the Discord Server of Deno.
This PR fixes #636

docs: fix Discord link in README

---

fresh.config.ts
plugins/error_handling.ts
plugins/session.ts
routes/api/items/[id].ts
routes/api/stripe-webhooks.ts
routes/api/users/[login]/index.ts
routes/api/users/[login]/items.ts
routes/api/vote.ts
utils/github.ts
utils/github_test.ts
utils/http.ts

It appears `std/http/http_errors` will be getting removed (see [here](https://github.com/denoland/deno_std/pull/3736)). Removing this dependency actually makes things cleaner.

refactor: remove use of `std/http/http_errors`

---

tasks/db_dump.ts
utils/db.ts
utils/posts.ts

[Deno 1.38](https://deno.com/blog/v1.38#v8-120) now supports [`Array.fromAsync()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fromAsync).

refactor: use `Array.fromAsync()`

---

deno.json

As per #648 
**Expected behavior** 
`init_stripe` script runs using the `STRIPE_SECRET_KEY` key defined in `.env` and successfully returns the `STRIPE_PREMIUM_PLAN_PRICE_ID` to stdout, as defined in the README.md
In this PR I have loaded the `.env` via the `--env` flag in the init:stripe task to match the desired behaviour oulined in the README.md

bug: load .env for init:stripe task

---

deno.json
e2e_test.ts

The e2e test runner was setting ENV from multiple sources leading cognitive complexity when reading, writing, and running tests. In particular, Github vars were passed as part of `deno task test` while STRIPE entities were not. 
1. Tests had different outcomes if run outside of the deno.json `test` task.
2. Tests were not atomically runnable as they were unaware of their required ENV vars. 
3. A users ENV could alter the outcome of tests
I created a `setupEnv` function which defines the base ENV state our application expects and provides a mechanism for mutating it into what a given test requires.
1. All tests start with the same base 
2. Tests are atomic
3. Deno task args minimally impact test outcomes (👀 `DENO_KV_PATH`)
6. User ENV minimally impacts test outcomes
```javascript
const …
```

chore: improve atomicity of E2E tests

---

README.md
fresh.config.ts

I didn't want to block you anymore, so I've created the PR as is.  Although I did just recently make a change to no longer hardcode the fresh version in my plugin, and it no longer references ga4 main. (In the unlikely event that anyone updates the project, we're now safe.)
I will try to finish the tests later this week, and then I think it's time for a `0.1.0` release, since I suppose not a lot will change after the tests are done.

feat: add ga4 plugin

---

.github/workflows/deploy.yml
README.md

docs: update "Deploy to Deno Deploy" guide

---

tasks/check_license.ts

Currently, when you add your own license to modified files, it will complain.
This changes the regex so that it can be multiline.

chore: allow license check to be multiline

---

components/Header.tsx

"Someone" broke the hamburger menu in #646.
This fixes the issue and cleans things up by making the CSS a bit more direct:
* I use https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-sibling-state to modify the `nav` directly.
* I add IDs to the hamburger and X components, and then use https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants to directly target them, in combination with peer.
FYI @hashrock since this restores the great work you did in #374.

fix: hamburger menu styling on smaller screens

---

routes/submit.tsx
routes/welcome.tsx

- fix url label
- added url input id
- removed empty `<p>` tag
- fix welcome page unused vars

fix: added hotfix for submit page

---

.github/workflows/ci.yml
deno.json

This task is no longer needed as the `--coverage` flag in the `deno test` automatically produces the lcov file.

chore: remove `cov:gen` task
